muvm-guest: Find actual path for muvm-server before trying to execute it
Otherwise this depends on where you run things from. In my case, I
would get:

  $ ./target/debug/muvm -- /bin/false
  Error: Failed to execute `muvm-server` as child process

  Caused by:
      No such file or directory (os error 2)

Signed-off-by: Stefano Brivio <sbrivio@redhat.com>